name: VMPE-BanItem
author: Zeao
version: 0.0.1-ALPHA9
api: [3.0.0-ALPHA6, 3.0.0-ALPHA7]
main: LDX\BanItem\Main
load: POSTWORLD
website: §cNot showing due to self-leak information.
commands:
  banitem:
    description: "BanItem main command."
    permission: banitem.command.banitem
    usage: "/banitem <ban/unban/list/report> [ID[:Damage]]"
permissions:
  banitem:
    default: op
    description: "Allows access to all BanItem features."
    children:
      banitem.bypass:
        default: op
        description: "Allows access to using banned items."
      banitem.command:
        default: op
        description: "Allows access to all BanItem commands."
        children:
          banitem.command.banitem:
            default: op
            description: "Allows access to the item command."
